[project]
name = "learning-sft-reinforced-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "axolotl>=0.18.0",
    "datasets>=4.8.4",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "notebook>=7.6.2",
    "torch==2.12.1",
    "torchao>=0.17.0",
    "tinybenchmarks @ git+https://github.com/felipemaiapolo/tinyBenchmarks",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]
