[project]
name = "learning-sft-reinforced-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "axolotl>=0.18.0",
    "torch==2.12.1",
    "torchao>=0.17.0",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]
